<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Common\" />
    <Folder Include="DTOs\" />
    <Folder Include="Interfaces\" />
    <Folder Include="Mappings\" />
    <Folder Include="Exceptions\" />
    <Folder Include="Validators\" />
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NewsPortalCMS.Domain\NewsPortalCMS.Domain.csproj" />
    <ProjectReference Include="..\NewsPortalCMS.Shared\NewsPortalCMS.Shared.csproj" />
  </ItemGroup>

</Project>
